### ISSUE TITLE
兄弟怎么删了sockstunnel?

### ISSUE THREAD

**Issue by luckypoem** [xxxsen/OhMyTunnel#1]
尽管我以前clone了sockstunnel：https://github.com/luckypoem/sockstunnel ,不过那个版本只是在linux vps上搭建成功。在mac上，我克隆该版本，在build目录，make遇错：
yudeMacBook-Air:build brite$ make
Scanning dependencies of target SocksTunnelLocal
[  2%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Json.cpp.o
In file included from /Users/brite/luckypoem-sockstunnel/src/CommonLib/Json.cpp:1:
In file included from /Users/brite/luckypoem-sockstunnel/src/CommonLib/Json.h:15:
In file included from /Users/brite/luckypoem-sockstunnel/src/CommonLib/Reader.h:5:
In file included from /Users/brite/luckypoem-sockstunnel/src/CommonLib/SharedPtr.h:22:
/Users/brite/luckypoem-sockstunnel/src/CommonLib/Mutex.h:102:21: error: 
      unknown type name 'pthread_barrier_t'
            typedef pthread_barrier_t BarrierID;
                    ^
1 error generated.
make[2]: *** [CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Json.cpp.o] Error 1
make[1]: *** [CMakeFiles/SocksTunnelLocal.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:build brite$

如何解决？
非常感谢你的答复！
（因为你删了sockstunnel，所以看不到你以前在issue里的答复了）

**Comment by xxxsen** [comment]
参考这个  https://www.oschina.net/question/214575_157215

另外用新的这个OhMyTunnel 吧。。这个编译起来应该也会容易一些。。

**Comment by xxxsen** [comment]
最最最最后一个。。可以去用下gost, 这个用起来很方便。。隧道工具我这边现在基本也都没维护了。。嘿嘿。。都是写着练练手而已。。

**Comment by xxxsen** [comment]
看起来像pb版本不同导致的。。重新生成proto文件试下

**Comment by luckypoem** [comment]
如何重新生成proto文件？

**Comment by xxxsen** [comment]
进到/src/protos/目录 运行 protoc --cpp_out=./ *.proto

**Comment by luckypoem** [comment]
还是不行，
...
[ 33%] Building CXX object server/sockv5/CMakeFiles/sockv5.dir/Session.cpp.o
In file included from /root/OhMyTunnel/src/protos/ProxyMsgPkg.h:4:0,
                 from /root/OhMyTunnel/src/server/sockv5/Session.cpp:12:
/root/OhMyTunnel/src/protos/ProxyMsg.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/root/OhMyTunnel/src/protos/ProxyMsg.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/root/OhMyTunnel/src/protos/ProxyMsg.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /root/OhMyTunnel/src/protos/ProxyMsgPkg.h:4:0,
                 from /root/OhMyTunnel/src/server/sockv5/Session.cpp:12:
/root/OhMyTunnel/src/protos/ProxyMsg.pb.h:1038:100: error: expected class-name before '{' token
 template <> struct is_proto_enum< ::proxy::msg::BIG_CMD> : ::google::protobuf::internal::true_type {};
                                                                                                    ^
/root/OhMyTunnel/src/protos/ProxyMsg.pb.h:1043:100: error: expected class-name before '{' token
 template <> struct is_proto_enum< ::proxy::msg::SUB_CMD> : ::google::protobuf::internal::true_type {};
                                                                                                    ^
server/sockv5/CMakeFiles/sockv5.dir/build.make:54: recipe for target 'server/sockv5/CMakeFiles/sockv5.dir/Session.cpp.o' failed
make[2]: *** [server/sockv5/CMakeFiles/sockv5.dir/Session.cpp.o] Error 1
CMakeFiles/Makefile2:179: recipe for target 'server/sockv5/CMakeFiles/sockv5.dir/all' failed
make[1]: *** [server/sockv5/CMakeFiles/sockv5.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
root@ar:~/OhMyTunnel/src/build#

你写ohmytunnel时，所用的protobuf的版本是什么？我好去https://github.com/google/protobuf/branches/stale ，编译相对应的protobuf的版本

**Comment by xxxsen** [comment]
2.5
luckypoem <notifications@github.com>于2018年4月14日 周六14:43写道：

**Comment by luckypoem** [comment]
hi.
我装了protobuf-2.5.0,make还是遇错：
...
[ 33%] Building CXX object server/sockv5/CMakeFiles/sockv5.dir/Session.cpp.o
In file included from /root/ohmytunnel/src/protos/ProxyMsgPkg.h:4:0,
                 from /root/ohmytunnel/src/server/sockv5/Session.cpp:12:
/root/ohmytunnel/src/protos/ProxyMsg.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/root/ohmytunnel/src/protos/ProxyMsg.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update.

root@ar:~# protoc --version
libprotoc 2.5.0
root@ar:~# 

"/root/ohmytunnel/src/protos/ProxyMsg.pb.h:12:2: error: #error This file was generated by a newer version of protoc.",怎么这里还是提示ProxyMsg.pb.h文件是由更高版本的protoc生成的？意思是说还需降低protoc的版本才行？难道protoc 2.5.0版还是太高了？
但是，你不是说你写OhMyTunnel时，所用的protoc的版本是2.5吗？

**Comment by xxxsen** [comment]
你有切到proto所在的目录执行吗？看下.cc文件的时间是不是你执行生成的时间。
luckypoem <notifications@github.com>于2018年4月15日 周日10:00写道：

**Comment by luckypoem** [comment]
hi.
或者你可上传linux vps 64bit上的可执行文件和mac上的可执行文件到releases 吗？

**Comment by xxxsen** [comment]
> hi.
> 或者你可上传linux vps 64bit上的可执行文件和mac上的可执行文件到releases 吗？

新写了另一个项目, 可以去看看哈。。这个基本不维护了。。
